apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumesafe-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: consumesafe.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consumesafe-service
                port:
                  number: 80

