$ANSIBLE_VAULT;1.1;AES256
31613736653031303933376666303533616266613835313239663465663334663330663766333865
3264663563623064613364306332613165343066616662310a643834303030613538323537363737
33626432656666373064323637343361323762666362313763366435303035613635336235373533
6134663731373134620a656538316662303161383033613435633865396232363232346534343335
63613634623138323566633238633066376635633030636632323964323865626433633339616535
31626234396434336639333838393836396636363836323337613435336666343364633134383735
39343934623365353839353461306630653366373532393936373136623738333830346232616530
33663034666436376238373763653237373862356662623431393032373966336465626339646435
6631
